"""Links

Revision ID: 0f86b4d30176
Revises: 479e9a91cbfb
Create Date: 2024-02-26 22:47:32.274516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f86b4d30176'
down_revision: Union[str, None] = '479e9a91cbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effects_id'), 'effects', ['id'], unique=False)
    op.create_index(op.f('ix_effects_name'), 'effects', ['name'], unique=False)
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sizes_id'), 'sizes', ['id'], unique=False)
    op.create_index(op.f('ix_sizes_name'), 'sizes', ['name'], unique=False)
    op.add_column('photos', sa.Column('size_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('effect_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_photos_description'), 'photos', ['description'], unique=False)
    op.create_index(op.f('ix_photos_effect_id'), 'photos', ['effect_id'], unique=False)
    op.create_index(op.f('ix_photos_size_id'), 'photos', ['size_id'], unique=False)
    op.create_index(op.f('ix_photos_url'), 'photos', ['url'], unique=False)
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_foreign_key(None, 'photos', 'sizes', ['size_id'], ['id'])
    op.create_foreign_key(None, 'photos', 'effects', ['effect_id'], ['id'])
    op.drop_column('photos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_url'), table_name='photos')
    op.drop_index(op.f('ix_photos_size_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_effect_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_description'), table_name='photos')
    op.drop_column('photos', 'url')
    op.drop_column('photos', 'effect_id')
    op.drop_column('photos', 'size_id')
    op.drop_index(op.f('ix_sizes_name'), table_name='sizes')
    op.drop_index(op.f('ix_sizes_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_effects_name'), table_name='effects')
    op.drop_index(op.f('ix_effects_id'), table_name='effects')
    op.drop_table('effects')
    # ### end Alembic commands ###
