"""Tags

Revision ID: 9fa4ddc43a79
Revises: 88bd2cb9cb6f
Create Date: 2024-02-25 17:15:57.706897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa4ddc43a79'
down_revision: Union[str, None] = '88bd2cb9cb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_tag_association',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'tag_id')
    )
    op.drop_table('image_tag_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tag_association',
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['photos.id'], name='image_tag_association_image_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='image_tag_association_tag_id_fkey')
    )
    op.drop_table('photo_tag_association')
    # ### end Alembic commands ###
